* 3D models I've made in OpenSCAD as a Nix Flake

** =.#beadsCuteElephant=

Remix of the [[https://www.printables.com/model/439440-cute-elephant-phone-stand][Cute Elephant Phone Stand]], the file =elephant_stand.stl= is
downloaded from Printables to make it into a bead.

** =.#beadsNixosLogo=

This is a bead that looks like the NixOS logo. Perfect for children to make
necklaces from.

** =.#businessCardHolder=

A simple holder for business cards.

** =.#cabinetHook=

A small hook for a cabinet.

** =.#garbageBinHook=

A small hook for hanging a garbage bin.

** Keychain shaped like climber holds

- =.#keychainClimberHoldKnob1=
- =.#keychainClimberHoldKnob2=
- =.#keychainClimberHoldKnob3=
- =.#keychainClimberHoldKnob4=
- =.#keychainClimberHoldKnob5=
- =.#keychainClimberHoldKnob6=

** =.#keychainLabel=

A simple keychain that I've made.

** =.#lampTopCorner=

This is a spare part for a lamp.

** =.#logitechCameraHolder=

This is a new chassis and holder for my disassembled Logitech webcam.

** =.#magnetsCuteElephant=

Remix of the [[https://www.printables.com/model/439440-cute-elephant-phone-stand][Cute Elephant Phone Stand]], the file =elephant_stand.stl= is
downloaded from Printables to make it into a fridge magnet.

** =.#paperFoodGarbageBagHolder=

Holder for food waste bags.

** =.#ringToy=

This is a fidget toy with rings.

** =.#roborockStopperForDryerStand=

This is a blocker to put on certain dryer stands to block robot vacuum
cleaners to get stuck on them.

** =.#routerHolder=

Holder brackets for my router to mount it to the wall.

** =.#shoppingCartFakeCoin=

A fake coin to use with shopping carts. The one from the store broke so I
made a new one ¯\_(ツ)_/¯.

** =.#sparvHooksNerfRifleWallHooks=

Custom hooks for Sparv.

** =.#tableStabilizier=

This is an object supposed to be put in each corner to make my kitchen table
more stable.

** =.#toothbrushHolder=

This is a toothbrush holder with drainage from reside water.

** =.#waterCo2MachineBottleStabilizer=

This is an object designed to put around the CO₂ bottle in my CO₂ water
machine, because if I don't push the bottle forwards 5mm it just doesn't work
at all.

** =.#webcamLevler=

This is an object to raise up the webcam so the front hook of the webcam
doesn't cover the screen.
