---
name: Check

'on':
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v18
      - uses: DeterminateSystems/flake-checker-action@v10

      - run: 'nix fmt . -- --check'
      - run: 'nix flake check'
