---
name: Check

'on':
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/flake-checker-action@v12

      - run: 'nix fmt . -- --check'
      - run: 'nix flake check'
